#include "SegmenterDlg.h"

#include "ui_SegmenterDlg.h" // This is auto-generated by CMake/Qt

SegmenterDlg::SegmenterDlg(QWidget* parent)
    : QDialog(parent)
    , ui(new Ui::SegmenterDialog)
{
	// Sets up all the widgets defined in the XML
	ui->setupUi(this);

	// Connect UI buttons to our custom signals
	connect(ui->btnUndo, &QPushButton::clicked, this, &SegmenterDlg::undoRequested);
	connect(ui->btnRedo, &QPushButton::clicked, this, &SegmenterDlg::redoRequested);
	connect(ui->btnClear, &QPushButton::clicked, this, &SegmenterDlg::clearRequested);

	// Connect standard OK/Cancel buttons
	connect(ui->buttonBox, &QDialogButtonBox::accepted, this, &QDialog::accept);
	connect(ui->buttonBox, &QDialogButtonBox::rejected, this, &QDialog::reject);

	// Optional: Emit a signal if weights or seed types change, so the algorithm auto-updates
	connect(ui->radioPositive, &QRadioButton::toggled, this, &SegmenterDlg::stateChanged);
	connect(ui->spinWs, QOverload<double>::of(&QDoubleSpinBox::valueChanged), this, &SegmenterDlg::stateChanged);
	connect(ui->spinWc, QOverload<double>::of(&QDoubleSpinBox::valueChanged), this, &SegmenterDlg::stateChanged);
	connect(ui->spinTau, QOverload<double>::of(&QDoubleSpinBox::valueChanged), this, &SegmenterDlg::stateChanged);
	
	this->setWindowFlags(this->windowFlags() | Qt::WindowStaysOnTopHint);
}

SegmenterDlg::~SegmenterDlg()
{
	delete ui;
}

double SegmenterDlg::getSpatialWeight() const
{
	return ui->spinWs->value();
}
double SegmenterDlg::getChromaticWeight() const
{
	return ui->spinWc->value();
}
double SegmenterDlg::getThreshold() const
{
	return ui->spinTau->value();
}
bool SegmenterDlg::isAddingPositiveSeeds() const
{
	return ui->radioPositive->isChecked();
}